# ===================================
#  Import/Export Behavior Config
# ===================================

export:
    title: renatio.maillog::lang.mail_log.export
    fileName: maillogs
    list: $/renatio/maillog/models/maillogexport/columns.yaml
    modelClass: Renatio\MailLog\Models\MailLogExport
    redirect: renatio/maillog/maillogs
    permissions: utilities.mail_logs.export
