# ===================================
# Filter Scope Definitions
# ===================================
scopes:

    is_sent:
        label: renatio.maillog::lang.field.is_sent
        type: switch
        conditions:
            - sent_at IS NULL
            - sent_at IS NOT NULL

    created_at:
        label: renatio.maillog::lang.field.created_at
        type: date
        modelScope: createdAtFilter
        showWeekNumber: true
